import { HEIGHT_DEFAULT, FONT_SIZE_DEFAULT, BORDER_RADIUS_DEFAULT, CORNERS as THEME_CORNERS } from './theme/globals';

export const HEIGHT = HEIGHT_DEFAULT;
export const FONT_SIZE = FONT_SIZE_DEFAULT;
export const BORDER_RADIUS = BORDER_RADIUS_DEFAULT;
export const CORNERS = THEME_CORNERS;
