export { LayoutProvider, Navbar, Footer, LanguageContext, ThemeContext, APP_NAME } from './Layout'
export { Home } from './Home'
export { Shop } from './Shop'
export { About } from './About'
export { Contact } from './Contact'
export { FAQ } from './FAQ'
export { Shipping } from './Shipping'
export { Returns } from './Returns'
export { Privacy } from './Privacy'
export { Terms } from './Terms'
